version: '2'
services:
  postgresql:
    image: 'postgres:latest'
    volumes:
      - './postgres_db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '1011'
      POSTGRES_DB: biblioteca
    ports:
      - '5432:5432'